"""expand_multi_agent_schema

Revision ID: 00f0b3cd6c11
Revises: 6405ca633c91
Create Date: 2026-02-25 18:06:10.452122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f0b3cd6c11'
down_revision: Union[str, Sequence[str], None] = '6405ca633c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tools',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=False),
    sa.Column('allowed_departments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tools_created_at'), 'agent_tools', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tools_is_active'), 'agent_tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_tools_is_deleted'), 'agent_tools', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_tools_name'), 'agent_tools', ['name'], unique=True)
    op.create_table('channel_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_identities_created_at'), 'channel_identities', ['created_at'], unique=False)
    op.create_index(op.f('ix_channel_identities_external_id'), 'channel_identities', ['external_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_user_id'), 'channel_identities', ['user_id'], unique=False)
    op.add_column('document_chunks', sa.Column('allowed_departments', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('documents', sa.Column('allowed_departments', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('query_logs', sa.Column('routed_to', sa.String(length=50), nullable=True))
    op.add_column('query_logs', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('query_logs', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'confidence_score')
    op.drop_column('query_logs', 'token_count')
    op.drop_column('query_logs', 'routed_to')
    op.drop_column('documents', 'allowed_departments')
    op.drop_column('document_chunks', 'allowed_departments')
    op.drop_index(op.f('ix_channel_identities_user_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_external_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_created_at'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_agent_tools_name'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_is_deleted'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_is_active'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_created_at'), table_name='agent_tools')
    op.drop_table('agent_tools')
    # ### end Alembic commands ###
