"""Add allowed_departments and content_format

Revision ID: 281c2b6eb360
Revises: 64af42714f0e
Create Date: 2026-03-03 17:31:43.076203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281c2b6eb360'
down_revision: Union[str, Sequence[str], None] = '64af42714f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('is_parent', sa.Boolean(), nullable=False))
    op.add_column('document_chunks', sa.Column('parent_chunk_id', sa.UUID(), nullable=True))
    op.alter_column('document_chunks', 'vector_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_document_chunks_is_parent'), 'document_chunks', ['is_parent'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'document_chunks', ['parent_chunk_id'], ['id'])
    op.add_column('documents', sa.Column('content_format', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_format')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_is_parent'), table_name='document_chunks')
    op.alter_column('document_chunks', 'vector_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('document_chunks', 'parent_chunk_id')
    op.drop_column('document_chunks', 'is_parent')
    # ### end Alembic commands ###
