"""add_stage_timings_to_querylog

Revision ID: 64af42714f0e
Revises: 00f0b3cd6c11
Create Date: 2026-02-25 18:54:26.499635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64af42714f0e'
down_revision: Union[str, Sequence[str], None] = '00f0b3cd6c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('stage_timings', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'stage_timings')
    # ### end Alembic commands ###
